src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Ad", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date doit être au bon format")
     * @Assert\GreaterThan("today", message="La date d'arrivée doit être ultérieure à aujourd'hui", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Attention, la date doit être au bon format")
     * @Assert\GreaterThan(propertyPath="startDate", message="La date de départ doit être postérieure à la date d'arrivée")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * Callback appelé à chaque réservation
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function prePersist()
    {
        if (empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }

        if (empty($this->amount)) {
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function isBookableDates()
    {
        $notAvailableDays = $this->ad->getNotAvailableDays();
        $bookingDays = $this->getDays();

        $formatDay = function ($day) {
            return $day->format('Y-m-d');
        };

        $days = array_map($formatDay, $bookingDays);

        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) return false;
        }

        return true;
    }

    /**
     * Permet de récupérer un array des journées qui correspondent à une réservation
     *
     * @return array de DateTime
     */
    public function getDays()
    {
        $resultat = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function ($dayTimestamp) {
            return new \Datetime(date('Y-m-d', $dayTimestamp));
        }, $resultat);

        return $days;
    }

    public function getId(): ? int
    {
        return $this->id;
    }

    public function getBooker(): ? User
    {
        return $this->booker;
    }

    public function setBooker(? User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ? Ad
    {
        return $this->ad;
    }

    public function setAd(? Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ? \DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ? \DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreatedAt(): ? \DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount(): ? float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ? string
    {
        return $this->comment;
    }

    public function setComment(? string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *  fields={"email"},
 *  message="Adresse email déjà utilisée")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Veuillez renseigner votre nom de famille")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez renseigner une URL valide")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @Assert\EqualTo(propertyPath="hash", message="Les mots de passes sont différents")
     */
    private $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="Votre description courte doit faire 10 caractères minimum")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre biographie doit faire 100 caractères minimum")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Ad", mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * Retourne le nom complet d'un user
     *
     * @return string
     */
    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }
    /**
     * Permet d'initiliser le slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initialiezSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ? int
    {
        return $this->id;
    }

    public function getFirstName(): ? string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ? string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ? string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ? string
    {
        return $this->picture;
    }

    public function setPicture(? string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ? string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ? string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ? string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ? string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getPasswordConfirm()
    {
        return $this->passwordConfirm;
    }

    public function setPasswordConfirm($passwordConfirm)
    {
        $this->passwordConfirm = $passwordConfirm;

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->userRoles->map(function($role) {
            return $role->getTitle();
        })->toArray();
        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function getPassword()
    {
        return $this->hash;
    }

    public function getSalt()
    { }

    public function getUsername()
    {
        return $this->email;
    }

    /**
     * Méthode implémtée de l'interface UserInterface qui permet
     * d'écraser des données sensibles stockées en clair dans l'objet
     *
     * @return void
     */
    public function eraseCredentials()
    { }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\ApplicationType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\DataTransformer\FrenchToDateTimeTransformer;

class BookingType extends ApplicationType
{
    private $transformer;

    public function __construct(FrenchToDateTimeTransformer $transformer)
    {
        $this->transformer = $transformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('startDate', TextType::class, $this->getConfiguration(
                "Date d'arrivée",
                "Votre date d'arrivée"
            ))
            ->add('endDate', TextType::class, $this->getConfiguration(
                "Date de départ",
                "Votre date de départ"
            ))
            ->add('comment', TextareaType::class, $this->getConfiguration(
                false,
                "(Optionnel) Ajoutez un commentaire à votre hôte si besoin...",
                ["required" => false]
            ));
        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            'validation_groups' => [
                'Default',
                'front'
            ]
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $request, ObjectManager $manager)
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $booking->setBooker($this->getUser())
                ->setAd($ad);

            //on vérifie que la réservation est possible, si le bien n'est pas déjà réservé sur l'une des dates
            if (!$booking->isBookableDates()) {
                $this->addFlash(
                    'warning',
                    "La réservation est impossible : une ou plusieurs dates est déjà prises"
                );
            } else {
                $manager->persist($booking);
                $manager->flush();

                return $this->redirectToRoute('booking_show', [
                    'id' => $booking->getId(),
                    'withAlert' => true,
                ]);
            }
        }

        return $this->render('booking/book.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher une réservation
     *
     * @Route("/booking/{id}", name="booking_show")
     * 
     * @param Booking $booking
     * @param Request $request
     * @param ObjectManager $manager
     * @return Response
     */
    public function show(Booking $booking, Request $request, ObjectManager $manager)
    {
        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setAd($booking->getAd())
                ->setAuthor($this->getUser());

            $manager->persist($comment);
            $manager->flush();

            $this->addFlash(
                'success',
                "Votre commentaire a bien été enregistré"
            );
        }

        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Révervation du logement
    {{ad.title}}
{% endblock %}

{% block stylesheets %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" rel="stylesheet" />
{% endblock %}

{% block body %}
    <div class="container">
        <h1>Réservation du logement :
            <em>{{ad.title}}</em>
        </h1>
        <p>Vous êtes sur le point de réserver le logement de
            <strong>{{ad.author.fullName}}</strong>, dites nous tout, on s'occupe du reste !</p>

        {{form_start(form)}}
        <div class="alert alert-light">
            <h2 class="h4">Commencez par nous dire quelles sont les dates qui vous intéressent</h2>
            <div class="row">
                <div class="col">
                    {{form_row(form.startDate)}}
                </div>
                <div class="col">
                    {{form_row(form.endDate)}}
                </div>
            </div>

            <h4 class="mt-3">Montant du séjour :
                <span id="amount">-</span>
                &euro;</h4>
            <span id="days">0</span>
            nuit à
            {{ad.price | number_format(2,',',' ')}}
            &euro; par nuit

            <h4 class="mt-4">Vous avez un commentaire ?</h4>
            {{form_row(form.comment)}}

        </div>

        <button class="btn btn-success mb-3" type="submit">Je réserve !</button>

        <h2>Vous avez terminé !</h2>
        <p>Vacances de rêve ? Hébergement pour le boulot ? Peu importe, on est avec vous</p>

        {{form_end(form)}}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>

    <script>
        !function (a) {
            a.fn.datepicker.dates.fr = {
                days: [
                    "dimanche",
                    "lundi",
                    "mardi",
                    "mercredi",
                    "jeudi",
                    "vendredi",
                    "samedi"
                ],
                daysShort: [
                    "dim.",
                    "lun.",
                    "mar.",
                    "mer.",
                    "jeu.",
                    "ven.",
                    "sam."
                ],
                daysMin: [
                    "d",
                    "l",
                    "ma",
                    "me",
                    "j",
                    "v",
                    "s"
                ],
                months: [
                    "janvier",
                    "février",
                    "mars",
                    "avril",
                    "mai",
                    "juin",
                    "juillet",
                    "août",
                    "septembre",
                    "octobre",
                    "novembre",
                    "décembre"
                ],
                monthsShort: [
                    "janv.",
                    "févr.",
                    "mars",
                    "avril",
                    "mai",
                    "juin",
                    "juil.",
                    "août",
                    "sept.",
                    "oct.",
                    "nov.",
                    "déc."
                ],
                today: "Aujourd'hui",
                monthsTitle: "Mois",
                clear: "Effacer",
                weekStart: 1,
                format: "dd/mm/yyyy"
            }
        }(jQuery);
        $(document).ready(function () {
            $('#booking_startDate, #booking_endDate').datepicker({
                language: 'fr',
                format: 'dd/mm/yyyy',
                datesDisabled: [{% for day in ad.notAvailableDays %}
                        "{{day.format('d/m/Y')}}",{% endfor %}],
                startDate: new Date()
            });

            $('#booking_startDate, #booking_endDate').on('change', calculateAmount);
        });

        function calculateAmount() {
            const endDate = new Date($('#booking_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const startDate = new Date($('#booking_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

            if (startDate && endDate && startDate < endDate) {
                const DAY_TIME = 24 * 60 * 60 * 1000;

                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DAY_TIME;
                const amount = days * {{ad.price}};

                $('#days').text(days);
                $('#amount').text(amount.toLocaleString('fr-FR'));
            }
        }
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n°{{booking.id}}{% endblock %}

{% block body %}

{% set ad = booking.ad %}
{% set author = ad.author %}

    <div class="container">
        <h1 class="my-5">Votre réservation n°{{booking.id}}</h1>

        {% if app.request.query.get('withAlert') %}
            <div class="alert-success">
                <h4 class="alert-heading">Bravo !</h4>
                <p>Votre réservation auprès de 
                <strong>
                    <a href="{{path('user_show', {'slug': author.slug})}}">{{author.fullName}}</a>
                </strong>
                pour l'annonce
                <strong>
                    <a href="{{path('ads_show', {'slug': ad.slug})}}">{{ad.title}}</a>
                </strong>
                a bien été prise en compte</p>
            </div>
        {% endif %}
        

        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Détails</h2>
                    <dl class="row">
                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{booking.id}}</dd>
                        <dt class="col-md-4">Date d'arrivé</dt>
                        <dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{booking.endDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{booking.duration}}</dd>
                        <dt class="col-md-4">Montant total</dt>
                        <dd class="col-md-8">{{booking.amount | number_format(2,',',' ')}} &euro;</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{booking.comment | default('Aucun commentaire')}}</dd>
                    </dl>

                    <hr/>

                    <h2 class="alert-heading">Votre hôte</h2>

                    <div class="row mb-3">
                        <div class="col-3">
                            <img src="{{author.picture}}" class="avatar avatar-medium" alt="Avatar de {{author.fullName}}">
                        </div>
                        <div class="col">
                        <h4>
                            <a href="{{path('user_show', {'slug': author.fullName }) }}">{{author.fullName}}</a>
                        </h4>
                        <span class="badge badge-primary">{{author.ads | length}} annonces</span>
                        </div>
                    </div>
                    {{author.description | raw}}

                    <a href="{{path('user_show', {'slug': author.slug})}}" class="btn btn-primary">Plus d'info sur {{author.firstName}}</a>
                </div>
            <div class="alert alert-light">
                <h2 class="alert-heading">Votre avis compte !</h2>
                {% if date() > date(booking.endDate) %}
                    {% set comment = booking.ad.commentFromAuthor(app.user) %}
                    {% if comment is not null %}
                    <blockquote>{{comment.content}}</blockquote>
                    <strong>Note : </strong>{% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                    {% else %}
                        {{form_start(form)}}
                        {{form_widget(form)}}
                        <button type="submit" class="btn btn-success">Confimer</button>
                        {{form_end(form)}} 
                    {% endif %}
                {% else %}
                    <p>Notation impossible pour le moment : votre voyage n'est pas encore passé</p>
                {% endif %}
                
            </div>
            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h2 class="alert-heading">Votre hébergement</h2>
                    <h4>
                        <a href="{{path('ads_show', {'slug': ad.slug}) }}">{{ad.title}}</a>
                    </h4>

                    <img src="{{ad.coverImage}}" alt="Image de {{ad.title}}" class="img-fluid">

                    {{ad.content | raw}}

                    <a href="{{path('ads_show', {'slug': ad.slug}) }}" class="btn btn-primary">Plus d'informations</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}